Feature/access menu keybinds
minecraft-access/minecraft-access pull request #343
Opened 2024-09-19 12:45 UTC by BrailleBennett

[//]: # (The changelog will be added into CHANGELOG.md file automatically by fast-forward workflow.)

[//]: # (Please delete unrelevant changelog sections.)

## Changelog

### New Features

### Feature Updates

### Bug Fixes

### Translation Changes

### Others

[//]: # (The `Development Chores` section won't be included as release notes, it's recorded for developers only.)

### Development Chores

[//]: # (## Keep Writting If You Have Anything Else To Say)

2024-09-20 02:28 UTC, BrailleBennett commented
https://github.com/khanshoaib3/minecraft-access-i18n/pull/41 must be merged prior to this PR.

2024-09-25 06:58 UTC, BrailleBennett commented
https://github.com/khanshoaib3/minecraft-access-i18n/pull/43 must be merged prior to this PR.

2024-10-02 13:21 UTC, boholder requested changes

2024-10-02 13:21 UTC, boholder commented on docs/keybindings.md
Please reformat the tables

2024-10-02 13:21 UTC, boholder commented on docs/config.md
> +10. [Narrator Menu](#access-menu)
`Narrator Menu` should be renamed to `Access Menu`, so does the corresponding title, or the `#access-menu` link won't work

2024-10-02 13:21 UTC, boholder commented on docs/features.md
> +This menu can be accessed by pressing the F4 key by default, and integrates a number of helper functions which can be executed from wintin the menu, or by using the individual hotkey directly.
Typo: `wintin`, `asside`

2024-10-02 13:21 UTC, boholder commented on docs/changelog.md
Changelog file shouldn't be changed, BTW the links are broken, I don't know when.

2024-10-02 13:21 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/access_menu/accessMenuGUI.java
First letter of class name should be uppercase

2024-10-02 13:21 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/access_menu/AccessMenu.java
> +if (!menuKey.isPressing() && menuKey.canOpenMenu() && isF3KeyNotPressed) {
format this line

2024-10-02 13:21 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/access_menu/AccessMenu.java
> +            if (KeyBindingsHandler.getInstance().narrateTarget.isPressed() && narrateTargetKey.canBeTriggered()) getBlockAndFluidTargetInformation();
`KeyBindingsHandler.getInstance()...isPressed()` can be omitted, `canBeTriggered()` method does same job

2024-10-02 13:21 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/access_menu/accessMenuGUI.java
Help me replace the head of `init` method with `super.init()`

2024-10-03 09:44 UTC, boholder approved these changes

2024-10-03 09:45 UTC, boholder commented
/fast-forward

2024-10-03 09:45 UTC, khanshoaib3 commented
\[Fast Forward CI\] feature/access-menu-keybinds merged into 1.21...\nNo changelogs found... Pushed the changes to origin.

2024-10-03 09:45 UTC, merged