Switch to Cloth Config
minecraft-access/minecraft-access pull request #347
Opened 2024-10-02 10:20 UTC by TheSuperGamer20578

## Changelog
### New Features
- Cloth Config is now accessible

### Feature Updates
- Cloth Config is now used for config

2024-10-02 11:45 UTC, boholder commented
Holy cow 75 files... 😂

2024-12-28 04:22 UTC, boholder commented
Make some of the cloth config widgets accessible:
the code responsible for all the widgets is in `compat/mixin/clothconfig`
its really just a case of reimplementing the vanilla methods responsible for making the widget keyboard focussable and narratable
here is the cloth config source https://github.com/shedaniel/cloth-config, iirc the [net.minecraft.client.gui.Narratable](https://linkie.shedaniel.dev/mappings?namespace=yarn&version=1.21&search=net.minecraft.client.gui.Narratable&allowFields=false&allowMethods=false&translateMode=none) interface is where all the magic happens

2024-12-29 05:13 UTC, boholder commented
Too many conflicts, I suggest waiting for #399, and #393 to be merged, and rework it on HEAD... Like I said, adding and deleting files while the directory is invalid do cause problems...

2024-12-29 05:13 UTC, boholder commented
Too many conflicts, I suggest waiting for #399, and #393 to be merged, and rework it on HEAD... Like I said, adding and deleting files while the directory is invalid do cause problems...

2024-12-29 22:58 UTC, TheSuperGamer20578 commented
I think it should still be safe to touch the Cloth Config specific stuff such as the mixins and new config class because these will just require a simple rename. As for everything else I think I'll just abandon my changes and start from scratch when I merge stuff in which I think I'll do quickly once #420 is merged, it's also possible that most of the conflicts are due to the package rename so I might be able to resolve those normally and only redo the files that have had significant changes.

2025-01-01 11:30 UTC, boholder commented
@TheSuperGamer20578 So the goal is make all the classes under [`me.shedaniel.clothconfig2.gui`](https://github.com/shedaniel/cloth-config/tree/v8/common/src/main/java/me/shedaniel/clothconfig2/gui) package narratable, right?

2025-01-01 13:03 UTC, boholder commented
Currently tracing: how to remove the color char ahead of "Yes" and "No" button text when narrating them (keep the color on GUI).
The text is from lang file of cloth-config: https://github.com/shedaniel/cloth-config/blob/a7639ae802bb1d0cdb8a49213b17bf141739ddc5/common/src/main/resources/assets/cloth-config2/lang/en_us.json#L33-L34
```
"text.cloth-config.boolean.value.true": "§aYes",
  "text.cloth-config.boolean.value.false": "§cNo",
```

2025-01-01 20:45 UTC, TheSuperGamer20578 commented
> @TheSuperGamer20578 So the goal is making all the classes under [`me.shedaniel.clothconfig2.gui`](https://github.com/shedaniel/cloth-config/tree/v8/common/src/main/java/me/shedaniel/clothconfig2/gui) package narratable, right?

Yes, or at least everything that autoconfig and thus our config uses. BTW if you haven't already noticed I added a modmenu entrypoint which allows us to get to the config menu without loading up a world, you can also access cloth's example config from there which uses some more exotic widgets.

2025-01-19 13:48 UTC, boholder commented
It seems that only two things are left:
- make `SubCategoryListEntry` navigable
- suppress "edit box:" prefix of narration of `SearchFieldEntry.EditBox`

2025-02-20 07:32 UTC, boholder commented
Note: configuration file has been changed from `config/minecraft-access/config.json` to `config/minecraft-access.json`

2025-02-25 02:59 UTC, boholder commented on common/build.gradle
> +    modApi 'me.shedaniel.cloth:cloth-config-fabric:17.0.144'
I hope #471 can be merged before so  `cloth config` library can make use of those new files

2025-02-25 12:14 UTC, boholder requested changes, later dismissed
Haven't write doc

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/MainClass.java
> +        Config config = Config.getInstance();
remove try catch

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/CameraControls.java
> -        enabled = map.isEnabled();
Does the `enabled` still being used?

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/CameraControls.java
> +        Config.CameraControls config = Config.getInstance().cameraControls;
Can we replace these fields with a record?

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/FallDetector.java
> +    private void loadConfig() {
This method can be omitted

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/FluidDetector.java
> +        config = Config.getInstance().accessMenu.fluidDetector;
Omit

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/PlayerWarnings.java
> +        if (config.playSound)
bracket

2025-02-25 12:14 UTC, boholder commented on fabric/build.gradle
> +    modImplementation 'com.terraformersmc:modmenu:13.0.0-beta.1'
@TheSuperGamer20578 I don't get why `modmenu` needs to be imported

2025-02-25 12:14 UTC, boholder commented on fabric/src/main/resources/fabric.mod.json
> +   "license": "GNU GPLv3",
wrong indentation

2025-02-25 12:14 UTC, boholder commented on fabric/src/main/resources/fabric.mod.json
> +  "environment": "*",
Wrong

2025-02-25 12:14 UTC, boholder commented on fabric/src/main/resources/fabric.mod.json
> +    "cloth-config": "*"
@TheSuperGamer20578 arbitrary version?

2025-02-25 12:14 UTC, boholder commented on neoforge/src/main/resources/META-INF/neoforge.mods.toml
> +type = "required"
version?

2025-02-25 12:14 UTC, boholder commented on neoforge/src/main/resources/META-INF/neoforge.mods.toml
> +config = "minecraft_access-compat.mixins.json"
mixins = [{config = "minecraft_access.mixins.json"},{config = "minecraft_access-compat.mixins.json"}]

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/mixin/ClientPlayNetworkHandlerMixin.java
empty file?

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/mixin/ScreenMixin.java
> +    private void debugLogFocusedComponent(Screen instance, ComponentPath path, Operation<Void> original) {
@TheSuperGamer20578 hey, do you think this is properly?

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/utils/BaseScreen.java
>          if (this.minecraft != null) this.minecraft.setScreen(previousScreen);
This is for old config menu, I think this can be deleted

2025-02-25 12:14 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/utils/system/MouseUtils.java
> +        if (config.macMouseFix) {
Just `Config.getInstance().mouseSimulation.macMouseFix`

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "minecraft_access.air.format": "Air is %s.",
sorted to here

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.category.playerWarnings": "Player warnings",
Player Warnings

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.areaMap.delayMilliseconds": "Delay (milliseconds)",
remove area map config

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.commandSuggestionNarratorFormat": "Command suggestion narrator format",
Command suggestion narration format

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.fallDetector.playAlternateSound": "Play alternate sound",
this option is unused

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.features.playerStatusEnabled": "Enable health & hunger",
Enable player status warning

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.inventoryControls.rowAndColumnFormat": "Crafting table slot format",
Crafting table slot narration format

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.menuFixEnabled": "Enable menu fix",
Enable menu fix (auto click top left corner when screen opened)

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.readCrosshair.disableSpeakingConsecutiveBlocks": "Disable speaking consecutive blocks",
Disable speaking consecutive same blocks

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.mouseSimulation.macMouseFix": "Use MacOS mouse fix",
Enable mouse fix (MacOS)

@TheSuperGamer20578 I wonder if cloth config allows me conditionally load option, I think it allows but in a complex way.

2025-02-25 12:14 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
> +  "text.autoconfig.minecraft-access.option.speechSettings.speechRate": "Speech rate",
Speech rate (MacOS)

2025-02-27 01:45 UTC, boholder commented
I decide to create yet another PR just for doc, I'll do it now.

2025-03-16 06:47 UTC, boholder commented
There are two dependency questions and one code opinion waiting for @TheSuperGamer20578 to answer... see the comments in "17 hidden items"

2025-03-22 14:53 UTC, boholder approved these changes

2025-03-22 14:54 UTC, merged