Refactor the POI system and some minor QOL improvements
minecraft-access/minecraft-access pull request #350
Opened 2024-10-07 00:51 UTC by Molitvan

The POIGroup class improves the POI system and allows for features like an object tracker and custom way points.

[//]: # (The changelog will be added into CHANGELOG.md file automatically by fast-forward workflow.)

[//]: # (Please delete unrelevant changelog sections.)

## Changelog

### Feature Updates
- Your pets, other's pets, bosses, players, and vehicles now have their own sounds
- Dropped item detection also now extends to projectiles on the ground which can be picked up like arrows and tridents

### Bug Fixes
- Some neutral mobs are now recognized as hostile when angry like wolves, instead of always being passive

[//]: # (The `Development Chores` section won't be included as release notes, it's recorded for developers only.)

### Development Chores
- Refactor the POI system with the POIGroup class

[//]: # (## Keep Writting If You Have Anything Else To Say)

2024-11-10 07:24 UTC, boholder requested changes

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/BlockFilter.java
> +// the reason for this existing is Java being weird and not having a built-in functional interface that takes 2 parameters and returns a single value
Nope, there is, BiFunction<T,U,R>

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/LockingHandler.java
> + * Locks on to the narest entity or block.<br><br>
I think "nearest" is the right one?...

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/POIBlocks.java
> +                group.clearBlocks();
I want to confirm: Have you decided to share detected targets between ticks or cache scanning result for other usage? If not, create and replace map instances will be better for avoiding unwanted timing issues, for example the map isn't cleared timely.

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/POIBlocks.java
It's really relaxing seeing POI classes being simpler and clearer... Thanks!

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/POIGroup.java
> +    public String getName() {
You can get rid of getter methods by announcing class fields as `public final`

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/POIGroup.java
> +    public void filterEntities(List<Entity> scannedEntities) {
Like what I said before, consider assigning new instances to class fields instead of reuse old one, unless you have other purposes that reuse old data.

2024-11-10 07:24 UTC, boholder commented on common/src/main/java/com/github/khanshoaib3/minecraft_access/features/point_of_interest/POIGroup.java
> +        if (result) blocks.put(pos, block);
Why a predicate method modifies content of class fields? It's not pure.

2024-11-19 00:49 UTC, boholder approved these changes, later dismissed
Nice.

2024-12-07 00:10 UTC, boholder submitted a review, later dismissed

2024-12-23 06:20 UTC, boholder approved these changes, later dismissed

2024-12-23 06:38 UTC, BrailleBennett approved these changes

2024-12-23 06:38 UTC, merged