Use Hugo and GH Pages for Docs
minecraft-access/minecraft-access pull request #354
Opened 2024-10-13 02:37 UTC by TheSuperGamer20578

The rendered page is visible on GH Pages of my fork: https://thesupergamer20578.github.io/minecraft-access/

## Changelog

### Others
- Moved docs onto GH Pages

2025-01-22 06:31 UTC, BrailleBennett approved these changes
While I can not vouch for the code itself, as I do not extensively know webpage development languages (e.g. css) I have stringently tested the site using multiple screen readers on different environments, and the site worked well on them all.

2025-01-24 02:49 UTC, boholder requested changes
1. Whether to add theme as git submodule
2. Some small glitches

2025-01-24 02:49 UTC, boholder commented on docs/content/changelog.md
> +Now there are [three workflows](https://github.com/khanshoaib3/minecraft-access/blob/1.21/.github/workflows):
sed -i s'@khanshoaib3/minecraft-access@minecraft-access/minecraft-access@g' *

2025-01-24 02:49 UTC, boholder commented on .gitmodules
> +[submodule "docs/themes"]
What pros and cons it is, comparing to remove the `theme` submodule and add `git clone --depth 1` to `docs` workflow.
The latter also save the existence of `dependabot.yml`.

2025-01-24 02:49 UTC, boholder commented on .github/workflows/docs.yml
> +  id-token: write
If we decide to use GH page... I don't understand the purpose of adding `id-token`, isn't it serves for interacting with other platforms?
https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings

2025-01-24 02:49 UTC, boholder commented on .github/workflows/docs.yml
> +  group: pages
Add proper comment (if the comment is what you want to achieve by using `concurrency`):
```
If new `docs` action is triggered, other previous already running `docs` actions will be canceled.
ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-concurrency-groups
```

2025-01-24 02:49 UTC, boholder commented on .github/workflows/docs.yml
> +      - "1.21"
Oops, now we have another hard coded string... but TBH I also can't find a handy ref of "default branch" (specifically, under this `on` part) after searching on the web, a replacement is triggering the action at every push and get default branch with api and compare in `if`, not what I want, I bet not yours too.

2025-01-24 02:49 UTC, boholder commented on .gitignore
> +/docs/.hugo_build.lock
If remove `themes` submodule, please add it as ignore dir too

2025-01-24 02:49 UTC, boholder commented on docs/content/_index.md
> +* Game version `1.21`, `1.20.6`, `1.20.4`, `1.20.1`, `1.19.3`
Please add `1.21.4`

2025-01-24 02:49 UTC, boholder commented on docs/content/_index.md
> +Each version of this mod will be pre-released on [GitHub](https://github.com/khanshoaib3/minecraft-access/releases) and announced in the [Playability Discord server](https://discord.gg/yQjjsDqWQX) fi
```markdown
Whenever the code is updated, the corresponding latest snapshot version will be published in the [Playability Discord server](https://discord.gg/yQjjsDqWQX). After gathering enough changes and feedback for making sure there is no serious bug, a tagged version will be released on [GitHub](https://github.com/khanshoaib3/minecraft-access/releases), [Modrinth](https://modrinth.com/mod/minecraft-access/versions) and [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/blind-accessibility/files).
```

2025-01-24 02:49 UTC, boholder commented on docs/content/_index.md
> +* [Primary developer's X account](https://x.com/shoaib_mk0) - You can follow the developer on X to get notified when a new update drops.
@khanshoaib3 Hey, are you still publishing the release info? Would it be good to remove this line to reduce your burden?

2025-01-24 02:49 UTC, boholder commented on docs/content/_index.md
> +## Known Issues
I suggest remove this part since I haven't seen Linux users report these issues, @khanshoaib3 what's your thoughts?

2025-01-24 02:49 UTC, boholder commented on docs/content/_index.md
> +* For development contributions, please read [CONTRIBUTING.md](https://github.com/khanshoaib3/minecraft-access/blob/1.21/CONTRIBUTING.md) for more details.
How about adding the `CONTRIBUTING` doc to the website?

2025-01-24 02:49 UTC, boholder commented on docs/content/config.md
> +| Targets         | [`slab`,&ZeroWidthSpace;`planks`,&ZeroWidthSpace;`block`,&ZeroWidthSpace;`stone`,&ZeroWidthSpace;`sign`] | Indicated what to be spoken
What the `&ZeroWidthSpace;` does? (yeah I understand it's purpose from name)

2025-01-24 02:49 UTC, boholder commented on docs/content/downloads.md
> +Minecraft Access is available for Fabric or Neoforge on Windows, Linux and Mac.
Fabric **and** Neoforge

2025-01-24 02:49 UTC, boholder commented on docs/content/_index.md
> +* On Windows and Linux operating systems ([Help us port the mod to macOS](https://github.com/khanshoaib3/minecraft-access/issues/22))
I intend to not mention #385 , but the `download.md` below has already included the macOS setup guide, so... how about also fix here?

2025-01-24 02:49 UTC, boholder commented on docs/content/setup/basic.md
> +The community member [@BrailleBennett](https://github.com/BrailleBennett) has created a modpack that contains everything you need to get started with Minecraft. If you wish to use this pack, go to it
its [**setup** guide **page**]

2025-01-24 03:01 UTC, boholder commented
BTW, the sounds in `sounds` page don't work in my local build with `hudo server`, here is the log

```
hugo.exe server
Watching for changes in E:\code\java\minecraft-access\docs\{content,themes}
Watching for config changes in E:\code\java\minecraft-access\docs\hugo.yml
Start building sites …
hugo v0.142.0-1f746a872442e66b6afd47c8c04ac42dc92cdb6f+extended windows/amd64 BuildDate=2025-01-22T12:20:52Z VendorInfo=gohugoio

WARN  Raw HTML omitted while rendering "E:/code/java/minecraft-access/docs/content/setup/advanced.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']
WARN  Raw HTML omitted while rendering "E:/code/java/minecraft-access/docs/content/changelog.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']

                   | EN
-------------------+-----
  Pages            | 17
  Paginator pages  |  0
  Non-page files   |  2
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Cleaned          |  0

Built in 8020 ms
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

2025-01-24 03:27 UTC, TheSuperGamer20578 commented on docs/content/config.md
> +| Targets         | [`slab`,&ZeroWidthSpace;`planks`,&ZeroWidthSpace;`block`,&ZeroWidthSpace;`stone`,&ZeroWidthSpace;`sign`] | Indicated what to be spoken
A zero-width space is a character which is completely invisible but tells the browser that it may wrap text there, without it that whole thing is treated as one gigantic word, and it tries its best to not wrap it, causing everything to go haywire.

2025-01-24 03:30 UTC, TheSuperGamer20578 commented on docs/content/_index.md
> +* For development contributions, please read [CONTRIBUTING.md](https://github.com/khanshoaib3/minecraft-access/blob/1.21/CONTRIBUTING.md) for more details.
I’m planning to add a contributing section among other docs changes in a future PR. This PR is concerned purely with moving the docs to GH Pages.

2025-01-24 03:31 UTC, sgmedev commented on .github/workflows/docs.yml
> +      - "1.21"
If we rename the branch, a workflow not running is the least of our worries.

2025-01-24 03:34 UTC, TheSuperGamer20578 commented on docs/content/changelog.md
> +Now there are [three workflows](https://github.com/khanshoaib3/minecraft-access/blob/1.21/.github/workflows):
I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 03:35 UTC, TheSuperGamer20578 commented on docs/content/_index.md
> +* Game version `1.21`, `1.20.6`, `1.20.4`, `1.20.1`, `1.19.3`
I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 03:35 UTC, TheSuperGamer20578 commented on docs/content/_index.md
> +Each version of this mod will be pre-released on [GitHub](https://github.com/khanshoaib3/minecraft-access/releases) and announced in the [Playability Discord server](https://discord.gg/yQjjsDqWQX) fi
I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 03:48 UTC, TheSuperGamer20578 commented on .gitmodules
> +[submodule "docs/themes"]
Using a submodule makes it a lot easier both for developers to preview their docs and for development of the theme itself since the theme will be there by default. It also simplifies the workflow not having to add a step to pull the repo. Dependabot also isn’t too bad, all we have to do is merge a PR whenever we update the theme.

2025-01-24 03:52 UTC, TheSuperGamer20578 commented on docs/content/_index.md
> +## Known Issues
I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 03:52 UTC, TheSuperGamer20578 commented on docs/content/setup/basic.md
> +The community member [@BrailleBennett](https://github.com/BrailleBennett) has created a modpack that contains everything you need to get started with Minecraft. If you wish to use this pack, go to it
I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 03:52 UTC, TheSuperGamer20578 commented on docs/content/downloads.md
> +Minecraft Access is available for Fabric or Neoforge on Windows, Linux and Mac.
I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 03:54 UTC, TheSuperGamer20578 commented on .github/workflows/docs.yml
> +  group: pages
The concurrency group tells it that if a new deployment starts while a now outdated deployment is running to cancel the outdated one.

2025-01-24 03:55 UTC, TheSuperGamer20578 commented on .github/workflows/docs.yml
> +  id-token: write
The deploy-pages action needs it. https://github.com/actions/deploy-pages https://gohugo.io/hosting-and-deployment/hosting-on-github/

2025-01-24 04:00 UTC, TheSuperGamer20578 commented
> ~BTW, the sounds in `sounds` page don't work in my local build with `hudo server`~ nope, it works, it just don't turning the cursor to hand icon when cursor is hovered. @BrailleBennett can you select the sound playing buttons with screen reader?

Nice catch, I shall fix that right now.

Those warnings are just saying there is some goofy HTML in those documents that Hugo is ignoring. I will fix them in my planned docs changes later.

2025-01-24 04:45 UTC, TheSuperGamer20578 commented
After some research, it turns out that the buttons use the default cursor by default and the pointer is meant exclusively for links. https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

2025-01-24 04:47 UTC, BrailleBennett requested changes
The branch on the two new GitHub repositories should be changed to "Main" to follow current accepted standards set forth by [GitHub](https://github.com/github/renaming) and [Git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

2025-01-24 05:38 UTC, TheSuperGamer20578 commented
> The branch on the two new GitHub repositories should be changed to "Main" to follow current accepted standards set forth by [GitHub](https://github.com/github/renaming) and [Git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

The first link is GitHub’s *internal* standards that they use for their own repositories; it is not intended to be an industry standard or used outside GitHub’s own repositories. The second link is simply stating that Git is adding an option to change the default. Please don’t give me complete bogus sources like this.

If you actually do your research and not try to give me the first completely unrelated search results, you will find that it’s merely a preference of some people which has led to organisations such as GitHub adding an *option* for users to *choose* what they want their default to be. There is nothing anywhere saying what we *should* name the master branch, *you* merely *want* it to be named a certain way.

For me the name `main` represents a combination of PR stunts and sucking up to the risk of people picking pointless fights like you are doing. Therefore, as someone who dislikes both of those things, I am not naming a branch that under any circumstances. If you absolutely must have an argument in the comments of a perfectly good pull request which I really hope you don’t and you can come up with a better name for the master branch, maybe we can come to a compromise.

2025-01-24 06:03 UTC, boholder commented on .gitmodules
> +[submodule "docs/themes"]
> for developers to preview their docs and for development of the theme itself

Agree, but there is no relative info in `CONTRIBUTION` doc (gonna add them?)
Or, how about don't make the theme as independent repo? We've already suffered from i18n repo.

2025-01-24 06:04 UTC, boholder commented on .gitmodules
> +[submodule "docs/themes"]
Sorry, messed up your reply, wrong clicking

2025-01-24 06:05 UTC, boholder commented on .github/workflows/docs.yml
> +  id-token: write
Please add relative info as comment

2025-01-24 06:07 UTC, boholder commented on .github/workflows/docs.yml
> +  group: pages
Thanks for the explaination, please add them as comment

2025-01-24 06:13 UTC, boholder commented on docs/content/config.md
> +| Targets         | [`slab`,&ZeroWidthSpace;`planks`,&ZeroWidthSpace;`block`,&ZeroWidthSpace;`stone`,&ZeroWidthSpace;`sign`] | Indicated what to be spoken
Thanks, can you add the reply as comment?

2025-01-24 06:13 UTC, boholder commented on docs/content/_index.md
> +* On Windows and Linux operating systems ([Help us port the mod to macOS](https://github.com/khanshoaib3/minecraft-access/issues/22))
> I’m planning to update docs in a future PR, this PR is just for putting the docs on to GH Pages.

2025-01-24 06:16 UTC, boholder commented
> The branch on the two new GitHub repositories

Two? You mean `theme` repo and https://github.com/minecraft-access/server-manifests ?

2025-01-24 06:18 UTC, boholder commented
> > The branch on the two new GitHub repositories should be changed to "Main" to follow current accepted standards set forth by [GitHub](https://github.com/github/renaming) and [Git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).
> For me the name `main` represents a combination of PR stunts and sucking up to the risk of people picking pointless fights like you are doing.

I'd like to do the renaming, just for avoiding things like yours reply...

2025-01-25 00:10 UTC, TheSuperGamer20578 commented on .gitmodules
> +[submodule "docs/themes"]
I’ll write a comprehensive guide on the docs among other things when I do my next docs PR. Unlike the I18N submodule, this one won’t have to be updated with code changes and therefore won’t suffer from the same pitfall of having two repos become out of sync. The reason why it has to be in a separate repo is that we want consistency across all our webpages when we make a proper landing page or if we decide to make a blog, server docs, or anything else in the future.

2025-01-25 00:12 UTC, TheSuperGamer20578 commented
> > > The branch on the two new GitHub repositories should be changed to "Main" to follow current accepted standards set forth by [GitHub](https://github.com/github/renaming) and [Git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).
> > > For me the name `main` represents a combination of PR stunts and sucking up to the risk of people picking pointless fights like you are doing.
> 
> I'd like to do the renaming, just for avoiding things like yours reply...

I would like to name it literally anything else for reasons stated above.

2025-01-30 07:04 UTC, TheSuperGamer20578 commented on docs/content/config.md
> +| Targets         | [`slab`,&ZeroWidthSpace;`planks`,&ZeroWidthSpace;`block`,&ZeroWidthSpace;`stone`,&ZeroWidthSpace;`sign`] | Indicated what to be spoken
I’m not sure if Markdown really likes comments in the middle of a table like that.

2025-01-30 07:10 UTC, TheSuperGamer20578 commented on .github/workflows/docs.yml
> +  group: pages
I don’t think that would be necessary since the documentation on the matter is already pretty clear. You can also see the documentation for it by hovering over it in IntelliJ.

2025-01-30 07:44 UTC, BrailleBennett approved these changes

2025-01-30 08:37 UTC, boholder approved these changes

2025-02-01 06:50 UTC, merged