Rewrite CI
minecraft-access/minecraft-access pull request #380
Opened 2024-11-07 13:10 UTC by BrailleBennett

[//]: # (The changelog will be added into CHANGELOG.md file automatically by fast-forward workflow.)

[//]: # (Please delete unrelevant changelog sections.)

## Changelog

### New Features

### Feature Updates

### Bug Fixes

### Translation Changes

### Others

[//]: # (The `Development Chores` section won't be included as release notes, it's recorded for developers only.)

### Development Chores

[//]: # (## Keep Writting If You Have Anything Else To Say)

2024-11-08 08:51 UTC, khanshoaib3 commented
uhh...are we removing the fast-forward ci?

2024-11-08 08:52 UTC, TheSuperGamer20578 commented
> uhh...are we removing the fast-forward ci?

Yes, https://discord.com/channels/843921862194364468/1291343800547147788

2024-11-08 09:11 UTC, khanshoaib3 commented
Oh I see. I would've personally kept the fast-forward but I don't mind.
And I like the idea of collecting the changelogs from PRs in the release workflow.
What threshold are you using? Like how do you determine which PRs to keep?

2024-11-08 11:14 UTC, TheSuperGamer20578 commented
> What threshold are you using? Like how do you determine which PRs to keep?

I'm going to have it add a `released` or `in-prerelease` label to PRs during a release. Prereleases will contain changelogs from everything since the last prerelease (everything with neither label) and full releases will contain changelogs from everything since the last full release (everything without the `released` label). This means that users who don't follow Prereleases can still get meaningful changelogs. A side effect of this labelling is that it also makes it clear whether a PR has been included in a release yet.

I probably should've and probably still will document this properly in the PR description, I just wasn't thinking of it when I wrote the description.

Alternatively I could use the merged timestamp but then I would need to find when the previous release was which sounds hard but might be posible with Git tags.

2024-11-20 08:45 UTC, boholder commented
TIL: GitHub supports mermaid syntax

2024-11-20 08:48 UTC, boholder requested changes

2024-11-20 08:48 UTC, boholder commented on gradle.properties
> -mod_version=1.8.0+1.21.1
This property is used in:
https://github.com/minecraft-access/minecraft-access/blob/7820fae574d450515181e8c1fde96a9c7306c63c/build.gradle#L37

2024-11-20 08:50 UTC, sgmedev commented on gradle.properties
> -mod_version=1.8.0+1.21.1
Not anymore, I made Gradle use the latest git tag which will always be the mod version

2024-11-20 08:56 UTC, boholder submitted a review, later dismissed

2024-12-22 05:29 UTC, boholder approved these changes, later dismissed
Sorry, I don't have enough knowledge to REVIEW this PR, there are too many details that I'm seeing for the first time.
I've skimmed through it roughly, assuming all the tool usage details are correct (supplemented by AI explanations), and don't see a problem.
I can sense how much effort you put into this PR from the number of force pushes and the beautiful structure of the CI, thanks for letting me appreciate this work of art, never expect the GitHub action can be written in such elegant form.

2024-12-22 05:29 UTC, boholder commented on .github/workflows/build.yml
> +        # language=bash
Let's add more comment:
"shopt" is specific to bash and enables extended pattern matching features.
The pattern in "cp" here uses extended globbing to match JAR files in the libs directory of all subdirectories except for those named common, while also excluding any JAR files that contain hyphens in their names.

2024-12-22 05:29 UTC, boholder commented on .github/workflows/push.yml
> +        # language=bash
I begin to wonder if `# language=bash` has real functions since I also see `# language=json`, are these for linting?

2024-12-22 05:32 UTC, TheSuperGamer20578 commented on .github/workflows/push.yml
> +        # language=bash
They tell IntelliJ to highlight the code in the string that comes after.

2024-12-22 23:12 UTC, TheSuperGamer20578 approved these changes

2024-12-22 23:12 UTC, merged