Removed some copied i18n strings and replaced them with vanilla versions
minecraft-access/minecraft-access pull request #397
Opened 2024-11-30 06:27 UTC by BrailleBennett

[//]: # (The changelog will be added into CHANGELOG.md file automatically by fast-forward workflow.)

[//]: # (Please delete unrelevant changelog sections.)

## Changelog
### Translation Changes
- Removed coppied strings that were already in use in vanilla, mainly the seperate color strings that Minecraft access had which vanilla translation already provides.

2024-11-30 06:36 UTC, BrailleBennett commented
Biggest issue is entity narration broke and I have no idea why. I didn't touch that part of i18n at all as you can see in the diff. I also didn't touch config keys, as #347 addresses them indirectly as cloth config uses vanilla keys where applicable already.

2024-12-01 04:39 UTC, boholder requested changes
LGTM

2024-12-01 04:39 UTC, boholder commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
Can you also remove these items in other language files?

2024-12-01 05:18 UTC, BrailleBennett commented on common/src/main/resources/assets/minecraft_access/lang/en_us.json
The items will be automatically removed from other language files by Weblate, since en_us is the source language.

2024-12-01 05:22 UTC, boholder approved these changes

2024-12-22 02:46 UTC, merged