Add an object tracker (POI target switching)
minecraft-access/minecraft-access pull request #399
Opened 2024-12-01 08:13 UTC by Molitvan

Closes #341 

This feature will do everything outlined in #341 allowing players to get a much better idea of their surroundings and give players control over what the locking feature targets.

I'll fill out the changelog once everything is done.

[//]: # (The changelog will be added into CHANGELOG.md file automatically by fast-forward workflow.)

[//]: # (Please delete unrelevant changelog sections.)

## Changelog

### New Features

### Feature Updates

### Bug Fixes

### Translation Changes

### Others

[//]: # (The `Development Chores` section won't be included as release notes, it's recorded for developers only.)

### Development Chores

[//]: # (## Keep Writting If You Have Anything Else To Say)

2025-01-12 04:08 UTC, boholder requested changes
In running, the new feature does not take effect for either block or entity, and the POI Block disappears.The POI Entity is valid. Can you provide a simple sequence of key pressing for testing?

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    public final POIGroup<BlockPos>[] groups = new POIGroup[] {
I bet extracting groups into separate class fields isn't what TSG wants.
For me, initializing this `POIGroup<BlockPos>[] groups` within static block is better. For example:
```java
static {
        POIGroup<BlockPos> oreGroup = ...
        POIBlocks.groups = {
            markedGroup,
            oreGroup,
            ......
        }
    }
```
But I noticed that you change the `groups` back to non-static, so can't do this for now.
Special groups like `markedGroup` does deserve an independent class field, while the others don't.

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
>      private ClientPlayerEntity player;
IntelliJ says this can be converted into local var

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/utils/KeyBindingsHandler.java
> +public KeyBinding objectTrackerPreviousItem;
fix the indentation

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/POIConfigMap.java
> +        m.setSpeakTargetPosition(false);
use `m.speakTargetPosition = false`, and remove the previous blank line

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/POIConfigMap.java
> +    private boolean speakTargetPosition;
init the value with  `= false;`

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
I don't understand why making other blocks group as exception

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    private List<BlockPos> lastScanResults = new ArrayList<>();
These two class fields can be moved to the front of methods

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIGroup.java
> +        this.nameSupplier = nameSupplier;
What's the benefit of getting the name dynamicly from a supplier instead of a static string?

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java
> +            MainClass.speakWithNarrator("No objects in current group", interupt);
Should use an I18N text instead

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/LockingHandler.java
> +        if (target instanceof Entity) {
```java
switch (target) {
            case Entity entity -> lockOnEntity(entity);
            case BlockPos blockPos -> lockOnBlock(blockPos);
            default -> {
                return;
            }
        }
```

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIEntities.java
> +            List<Entity> currentScanResults = new ArrayList<>();
Fix the indentation

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +        lastScanResults = currentScanResults;
You sure assigning this after `currentScanResults = new ArrayList<>();`? Both two are empty lists now. Doesn't sounds like what the `lastScanResults` name means, I've thought it's for saving the previous results.

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/utils/KeyBindingsHandler.java
> +                I18n.translate("minecraft_access.point_of_interest.object_tracker.group_name")
These four translation keys, "minecraft_access.point_of_interest.object_tracker.group_name", don't exist

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java
> +            MainClass.speakWithNarrator("Targeting nearest object", true);
Should use an I18N text instead

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java
> +            MainClass.speakWithNarrator(I18n.translate("minecraft_access.other.end_of_list"), true);
In fact you can make the group switching an infinity loop, with `index = (index + groups.size()) % groups.size()`. So you can save two translations "start of list" "end of list" and making the user experience a little better. Speaking of which, we can also apply this on slot groups in Inventory Control.

2025-01-12 04:08 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/ObjectTracker.java
> +    private Keystroke targetNearestObjectKeyPressed = new Keystroke(() -> KeyUtils.isAnyPressed(KeyBindingsHandler.getInstance().targetNearestObject), Keystroke.TriggeredAt.PRESSED);
These four fields can be `final`

2025-01-12 05:10 UTC, TheSuperGamer20578 commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    public final POIGroup<BlockPos>[] groups = new POIGroup[] {
Extracting groups into separate fields is perfectly fine, and IMO is the best way to handle this. I actually generally don’t like static blocks because often they end up just duplicating code by separating the declaration and assignment where these could be combined into one statement.

Now that I think about it, an enum might be even better for this if most groups need to be accessed separately since enums let you both iterate over all their variants and get individual variants without any duplication or spreading stuff out at all, you could define such an enum something like this:
```java
enum BlockGroups {
    FLUIDS(
        SoundEvents.BLOCK_NOTE_BLOCK_BIT.value(),
        2f,
        pos -> this.detectFluidBlocks && world.getBlockState(pos).getBlock() instanceof FluidBlock && PlayerUtils.isNotInFluid() && world.getFluidState(pos).getLevel() == 8
    ),
    FUNCTIONAL(
        SoundEvents.BLOCK_NOTE_BLOCK_BIT.value(),
        2f,
        pos -> world.getBlockState(pos).getBlock() instanceof ButtonBlock || world.getBlockState(pos).getBlock() instanceof LeverBlock || poiBlockPredicates.stream().anyMatch(p -> p.test(world.getBlockState(pos)))
    );

    public final POIGroup<BlockPos> group;

    BlockGroups(SoundEvent sound, float soundPitch, Predicate<BlockPos> predicate) {
        group = new POIGroup<>(sound, soundPitch, predicate);
    }
}
```

2025-01-17 13:10 UTC, boholder commented
I suggest you making this PR to be merged before making additional POI changes, for avoiding creating a big PR.

2025-01-17 18:30 UTC, Molitvan commented
> In running, the new feature does not take effect for either block or entity, and the POI Block disappears.The POI Entity is valid. Can you provide a simple sequence of key pressing for testing?
Weird. Works mostly fine for me and the testers. Make sure to increase your POI detecting range because the objects will disappear from the list if they're out of range.

Example test:
- Summon a pig and a sheep, place a crafting table and a furnace
- Use CTRL + PGUP/PGDOWN to scroll through groups. In this case, the groups should be passive entities, blocks with interface and other blocks.
- Use PGUP and PGDOWN to scroll to objects in a group. While scrolling, you should hear the object's name and a positional sound comming from where the object is.
- Pressing HOME should repeat the narration and sound
- Press END to target the nearest object
- At any point, use the locking feature to lock onto the current object

2025-01-17 18:31 UTC, Molitvan commented
> IntelliJ says this can be converted into local var
I didn't change that line. Don't know why Git thinks I did.

> You sure assigning this after currentScanResults = new ArrayList<>();? Both two are empty lists now. Doesn't sounds like what the lastScanResults name means, I've thought it's for saving the previous results.
currentScanResults gets populated in the checkBlock methods. The current scan is the one currently running in the checkBlock methods, and last scan is the last completed scan.

> In fact you can make the group switching an infinity loop, with index = (index + groups.size()) % groups.size(). So you can save two translations "start of list" "end of list" and making the user experience a little better. Speaking of which, we can also apply this on slot groups in Inventory Control.
I usually don't really like wrapping lists, but in this case it may actually be a good idea. Also please don't apply this to inventory controls because it will make it very confusing. What we should probably do for the inventory controls though is add keys for snapping to the most left/right and most up/down slots in the current slot group.

2025-01-17 18:32 UTC, Molitvan commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    public final POIGroup<BlockPos>[] groups = new POIGroup[] {
> Extracting groups into separate fields is perfectly fine, and IMO is the best way to handle this. I actually generally don’t like static blocks because often they end up just duplicating code by separating the declaration and assignment where these could be combined into one statement.
> 
> Now that I think about it, an enum might be even better for this if most groups need to be accessed separately since enums let you both iterate over all their variants and get individual variants without any duplication or spreading stuff out at all, you could define such an enum something like this:
> 
> ```java
> enum BlockGroups {
>     FLUIDS(
>         SoundEvents.BLOCK_NOTE_BLOCK_BIT.value(),
>         2f,
>         pos -> this.detectFluidBlocks && world.getBlockState(pos).getBlock() instanceof FluidBlock && PlayerUtils.isNotInFluid() && world.getFluidState(pos).getLevel() == 8
>     ),
>     FUNCTIONAL(
>         SoundEvents.BLOCK_NOTE_BLOCK_BIT.value(),
>         2f,
>         pos -> world.getBlockState(pos).getBlock() instanceof ButtonBlock || world.getBlockState(pos).getBlock() instanceof LeverBlock || poiBlockPredicates.stream().anyMatch(p -> p.test(world.getBlockState(pos)))
>     );
> 
>     public final POIGroup<BlockPos> group;
> 
>     BlockGroups(SoundEvent sound, float soundPitch, Predicate<BlockPos> predicate) {
>         group = new POIGroup<>(sound, soundPitch, predicate);
>     }
> }
> ```

I have no idea how that code works lol

2025-01-17 18:34 UTC, Molitvan commented
> I suggest you making this PR to be merged before making additional POI changes, for avoiding creating a big PR.
Agreed

2025-01-17 22:25 UTC, TheSuperGamer20578 commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    public final POIGroup<BlockPos>[] groups = new POIGroup[] {
Java enums are able to have constructors, fields, and methods like any other class, all you have to do is put a semicolon after the last variant. When you define a constructor, you have to put the constructor parameters in parentheses after every variant as seen in my example. Every enum variant is an instance of the enum, so in this example if you wanted to access the fluids group, for example, you would write `BlockGroups.FLUIDS.group`.

2025-01-24 03:27 UTC, boholder commented
> > IntelliJ says this can be converted into local var
> 
> I didn't change that line. Don't know why Git thinks I did.

Help all of us, fix it with `alt` + `enter`, thanks.

> > You sure assigning this after currentScanResults = new ArrayList<>();? Both two are empty lists now. Doesn't sounds like what the lastScanResults name means, I've thought it's for saving the previous results.
> 
> currentScanResults gets populated in the checkBlock methods. The current scan is the one currently running in the checkBlock methods, and last scan is the last completed scan.

As long as you confirm the logic is right, the naming of these variables is good to me.

2025-01-31 06:53 UTC, boholder commented
@Molitvan There are unresolved questions, would we discuss about them before reviewing?

2025-02-11 01:39 UTC, boholder commented
@Molitvan There are some places that haven't been settled:

1. [Change poi groups to enum](https://github.com/minecraft-access/minecraft-access/pull/399#discussion_r1920828276), maybe @TheSuperGamer20578 can directly provide the code for you to patch.
2. https://github.com/minecraft-access/minecraft-access/pull/399#discussion_r1912351998
3. Maybe duplicate with 1: https://github.com/minecraft-access/minecraft-access/pull/399#discussion_r1912352280
4. https://github.com/minecraft-access/minecraft-access/pull/399#discussion_r1912354565

2025-03-06 01:52 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
> I don't understand why making other blocks group as exception

: Because if it puts everything in like the other groups, you'll end up with a billion different things in there and it'll turn into an unusable mess

2025-03-06 01:52 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIGroup.java
> +        this.nameSupplier = nameSupplier;
> What's the benefit of getting the name dynamicly from a supplier instead of a static string?

: I couldn't get i18n to work properly when using a static string. Also I didn't test this, but I think changing the language also wouldn't work when using a static string

2025-03-18 22:11 UTC, Molitvan commented
Is this done now or are there still things that need changes? I saw discussion about switching to enums on Discord.

2025-03-19 00:51 UTC, boholder commented
> Is this done now or are there still things that need changes?

Still WIP in my perspective, see https://github.com/minecraft-access/minecraft-access/compare/dev...boholder:minecraft-access:poi-object-tracker

2025-03-19 05:48 UTC, Molitvan commented
> > Is this done now or are there still things that need changes?
> 
> Still WIP in my perspective, see [dev...boholder:minecraft-access:poi-object-tracker](https://github.com/minecraft-access/minecraft-access/compare/dev...boholder:minecraft-access:poi-object-tracker)

Ok from what I can tell it's like I said on Discord. It's feature-complete, but there's a bunch of refactoring left to do.

Oh and btw if I can help with anything, just say.

2025-03-22 09:05 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    private boolean otherBlocksFilter(BlockPos pos) {
@Molitvan Can you explain the idea of having an "other blocks group"?
I can't get this filter method's purpose: 1. it involves its "parent" - "otherBlocksGroup" 2. it compares block type instead of block position

2025-03-22 09:22 UTC, Molitvan commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    private boolean otherBlocksFilter(BlockPos pos) {
> @Molitvan Can you explain the idea of having an "other blocks group"? I can't get this filter method's purpose: 1. it involves its "parent" - "otherBlocksGroup" 2. it compares block type instead of block position

The other blocks group contains the closest of every block that wasn't picked up by any other POI group around the player. This is useful when trying to find something that is not considered a POI, for example until we make a proper trees category, this is a decent way to find trees. It compares block type because again, it contains only one of every block type around the player.

2025-03-22 10:15 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    private boolean otherBlocksFilter(BlockPos pos) {
> The other blocks group contains the closest of every block that wasn't picked up by any other POI group around the player.

Thanks, I added the description to code

```java
    /**
     * The other blocks group contains the closest of every block
     * that wasn't picked up by any other POI group around the player.
     * This is useful when trying to find something that is not considered a POI,
     * for example until we make a proper trees category, this is a decent way to find trees.
     */
    private final POIGroup<BlockPos> otherBlocksGroup = new POIGroup<>(
        "minecraft_access.point_of_interest.group.otherBlocks",
            this::blockIsNotAirAndNotContainedInGroupYet
    );

    private boolean blockIsNotAirAndNotContainedInGroupYet(BlockPos pos) {
        BlockState state = WorldUtils.getBlockState(pos);
        Set<Block> groupContainedBlockTypes = otherBlocksGroup.getItems().stream()
                .map(p -> WorldUtils.getBlockState(p).getBlock()).collect(Collectors.toSet());
        boolean blockAlreadyInGroup = groupContainedBlockTypes.contains(state.getBlock());
        return !state.isAir() && !blockAlreadyInGroup;
    }
```

2025-03-22 10:35 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +    public final POIGroup<BlockPos>[] groups = new POIGroup[] {
@TheSuperGamer20578 `POIGroup` can't be enum since I want to dynamically create its instances from user custom config in the future. I managed to collect builtin groups into enum

2025-03-22 10:39 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
@Molitvan Wait, it seems that the content of other blocks group isn't included in "lastScanResults" for locking feature, so can I make conclusion that the "otherBlocksGroup" is unused, for now, in scope of this PR?

2025-03-22 11:41 UTC, Molitvan commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
> @Molitvan Wait, it seems that the content of other blocks group isn't included in "lastScanResults" for locking feature, so can I make conclusion that the "otherBlocksGroup" is unused, for now, in scope of this PR? Maybe deleting it is better?

The other blocks group is fully complete and being used. This gives me the impression that you didn't even run the PR build. Could you please do that? You can't properly test features by just looking at the code.

2025-03-22 11:51 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
> The other blocks group is fully complete and being used.

I'm checking the code in IDE. The "otherBlocksGroup" has three usages and all of three are for modifying group content, the only "get" usage is in its filter method.

2025-03-22 11:58 UTC, Molitvan commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
> > The other blocks group is fully complete and being used.
> 
> I'm checking the code in IDE. The "otherBlocksGroup" has three usages and all of three are for modifying group content, the only "get" usage is in its filter method.

That's right, but it is included in the POIBlocks groups list, which means it's included in the object tracker. The get method isn't used directly, but it is used when selected in the object tracker, just like every other group.

Again, I request you please run the build, because it's impossible to properly review features without doing that.

Open any world and stand on the ground. You'll notice the other blocks group at the bottom of the object tracker, fully functioning. That looks very used to me.

2025-03-22 12:01 UTC, boholder commented on common/src/main/java/org/mcaccess/minecraftaccess/features/point_of_interest/POIBlocks.java
> +            if (group.add(blockPos) && group != otherBlocksGroup) {
> That's right, but it is included in the POIBlocks groups list, which means it's included in the object tracker. The get method isn't used directly, but it is used when selected in the object tracker, just like every other group.

You're right, sorry for not fully reading the code.

2025-03-22 13:28 UTC, boholder approved these changes
I tested all the POI features and new tracker features in dev env.

2025-03-22 13:30 UTC, merged