1.21.4
minecraft-access/minecraft-access pull request #409
Opened 2024-12-21 12:07 UTC by boholder

Game upgrade to 1.21.4

2024-12-22 04:55 UTC, TheSuperGamer20578 requested changes
Please write a proper changelog.

2024-12-22 04:55 UTC, TheSuperGamer20578 commented on docs/mod-compatibility.md
Please don't link to the unfinished docs. This will only create merge conflicts with the docs because this is not the proper way of linking.

2024-12-22 04:55 UTC, TheSuperGamer20578 commented on gradle.properties
> +yarn_mappings_patch_neoforge_version=1.21+build.4
No newline at end of file.

2024-12-22 06:36 UTC, boholder commented
> Please write a proper changelog. I will conduct a more comprehensive review later, this is just some preliminary things that stood out to me.

I can't figure out what category the game version updates belongs to, so I'd prefer to omit it in changelog.

2024-12-22 06:36 UTC, boholder commented on gradle.properties
> +yarn_mappings_patch_neoforge_version=1.21+build.4
Yeah, added

2024-12-22 06:39 UTC, boholder commented on docs/mod-compatibility.md
Ok, reverted

2024-12-22 07:04 UTC, TheSuperGamer20578 commented
> > Please write a proper changelog. I will conduct a more comprehensive review later, this is just some preliminary things that stood out to me.
> 
> I can't figure out what category the game version updates belongs to, so I'd prefer to omit it in changelog.

I would probably put it in it's own section, otherwise the new CI can handle stuff that's not under any section. This change is far too important to completely omit from the changelog.

2024-12-23 05:39 UTC, TheSuperGamer20578 approved these changes

2024-12-23 05:39 UTC, merged