fix: the new "Mac Mouse Fix" doesn't have default value which causes NPE
minecraft-access/minecraft-access pull request #422
Opened 2024-12-29 06:10 UTC by boholder

2024-12-29 06:16 UTC, TheSuperGamer20578 requested changes
Is the default not set on line 28 (which is also erroneously indented with a tab)?
```java
m.macMouseFix = false;
```

2024-12-29 06:16 UTC, TheSuperGamer20578 commented on common/src/main/java/org/mcaccess/minecraftaccess/config/config_maps/MouseSimulationConfigMap.java
> +	private Boolean macMouseFix = false;
This line is indented with a tab, it should be indented with four spaces.
```suggestion
    private Boolean macMouseFix = false;
```

2024-12-29 06:36 UTC, boholder commented
> Is the default not set on line 28 (which is also erroneously indented with a tab)?
> 
> ```java
> 
> m.macMouseFix = false;
> 
> ```

Weird, it's formatted normally in the IDE. Do we encounter sort of invisible characters (I remember there are related attacking)

2024-12-29 09:20 UTC, BrailleBennett requested changes, later dismissed
Disregard

2024-12-29 09:20 UTC, BrailleBennett commented
Ugh, wrong PR

2024-12-29 09:30 UTC, BrailleBennett requested changes
You must put somehting in the PR description. If it is fully empty the CI will error.

2024-12-29 09:52 UTC, TheSuperGamer20578 commented
> > Is the default not set on line 28 (which is also erroneously indented with a tab)?
> > 
> > ```java
> > 
> > m.macMouseFix = false;
> > 
> > ```
> 
> Weird, it's formatted normally in the IDE. Do we encounter sort of invisible characters (I remember there are related attacking)

It's a tab character, it looks the same as four spaces in your current IDE configuration but is actually oe character which you will notice when you try to highlight it. On GitHub it looks like stuff is indented wrongly because it displays a tab as eight spaces for some reason, this inconsistency in tab width between viewers is why it's imparative not to use tabs anywhere.

2024-12-29 11:47 UTC, boholder commented
> It's a tab character

So that's a good rule for linter.... replace tab with spaces

2025-01-04 04:45 UTC, TheSuperGamer20578 approved these changes

2025-01-06 05:45 UTC, BrailleBennett approved these changes

2025-01-06 09:37 UTC, merged