Custom Sounds V0.1
minecraft-access/minecraft-access pull request #424
Opened 2024-12-29 09:18 UTC by rstrunk

2024-12-29 09:29 UTC, BrailleBennett requested changes
You must fill out the pull request changelog template as this is what is added to the changelog. The description can't be empty, or the CI breaks.

2024-12-29 09:42 UTC, TheSuperGamer20578 requested changes
Please merge or rebase the latest changes from the `1.21` branch into your branch. This will involve moving any new classes to the new `org.mcaccess.minecraftaccess` base package. It would also be great if you could run your IDE's autoformatter on your changes.

2025-01-03 23:11 UTC, closed without merging

2025-01-03 23:13 UTC, rstrunk commented
Closing this PR and putting up another one because I made a few more changes.

2025-01-03 23:28 UTC, TheSuperGamer20578 commented
FYI you do not need to create a new PR every time you make changes, if you push to the branch you created a PR from GItHub will pick it up automatically, this also makes it easier for us to keep track of changes between reviews and keeps everything in one neat thread.